# =============================================================================
# ANPR / Vehicle License Plate Detection Configuration (YOLOv8 Format)
# =============================================================================

path: ../datasets/license_plates
train: images/train
val: images/val
test: images/test

names:
  0: license_plate
